// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Service.Photos.Dal.Migrations
{
    [DbContext(typeof(PhotosContext))]
    [Migration("20200129121835_PhotoPackageIndex")]
    partial class PhotoPackageIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int>("AttachedBy")
                        .HasColumnName("ATTACHED_BY");

                    b.Property<long>("AttachmentId")
                        .HasColumnName("ATTACHMENT_ID");

                    b.Property<string>("ErrorCode")
                        .HasColumnName("ERROR_CODE")
                        .HasMaxLength(1000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("FoundDate")
                        .HasColumnName("FOUND_DATE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool?>("IsSaved")
                        .HasColumnName("IS_SAVED");

                    b.Property<double>("Latitude")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnName("LONGITUDE");

                    b.Property<int?>("ParentPhotoTypeId")
                        .HasColumnName("PARENT_PHOTO_TYPE_ID");

                    b.Property<long>("PhotoPackageId")
                        .HasColumnName("PACKAGE_PHOTO_ID");

                    b.Property<int>("PhotoTypeId")
                        .HasColumnName("PHOTO_TYPE_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .IsUnique();

                    b.HasIndex("PhotoPackageId");

                    b.ToTable("APPLICATION_PHOTO");
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhotoHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("ErrorCode")
                        .HasColumnName("ERROR_CODE")
                        .HasMaxLength(1000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("FoundDate")
                        .HasColumnName("FOUND_DATE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IS_DELETED");

                    b.Property<double>("Latitude")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnName("LONGITUDE");

                    b.Property<long>("PackageHistoryId")
                        .HasColumnName("PACKAGE_HISTORY_ID");

                    b.Property<int?>("ParentPhotoTypeId")
                        .HasColumnName("PARENT_PHOTO_TYPE_ID");

                    b.Property<int>("PhotoTypeId")
                        .HasColumnName("PHOTO_TYPE_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.HasKey("Id");

                    b.HasIndex("PackageHistoryId");

                    b.ToTable("APPLICATION_PHOTO_HISTORY");
                });

            modelBuilder.Entity("Service.Photos.Dal.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<byte[]>("MiniPhoto")
                        .HasColumnName("MINI_PHOTO");

                    b.Property<byte[]>("Photo")
                        .HasColumnName("PHOTO");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.Property<Guid?>("UUID")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("ATTACHMENT");
                });

            modelBuilder.Entity("Service.Photos.Dal.CurrentPhotoRequired", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int>("CreditType")
                        .HasColumnName("CREDIT_TYPE_KEY");

                    b.Property<bool?>("IsDigital")
                        .HasColumnName("IS_DIGITAL");

                    b.Property<bool?>("IsRemoteSign")
                        .HasColumnName("IS_REMOTE_SIGN");

                    b.Property<bool>("IsRequired")
                        .HasColumnName("IS_REQUIRED");

                    b.Property<int>("PhotoTypeId")
                        .HasColumnName("PHOTO_TYPE_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.Property<bool>("Visibility")
                        .HasColumnName("VISIBILITY");

                    b.HasKey("Id");

                    b.ToTable("CURRENT_PHOTO_REQUIRED");
                });

            modelBuilder.Entity("Service.Photos.Dal.CurrentPhotoType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("CODE")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(255);

                    b.Property<int?>("DocumentType")
                        .HasColumnName("DOC_TYPE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnName("ORDER");

                    b.Property<int?>("ParentId")
                        .HasColumnName("PARENT_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.Property<int>("TypeId")
                        .HasColumnName("TYPE_ID");

                    b.HasKey("Id");

                    b.ToTable("CURRENT_PHOTO_TYPE");
                });

            modelBuilder.Entity("Service.Photos.Dal.PhotoPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<long>("ApplicationId")
                        .HasColumnName("APPL_ID");

                    b.Property<DateTime?>("AproveDate")
                        .HasColumnName("APROVE_DATE");

                    b.Property<DateTime?>("ErrorDate")
                        .HasColumnName("ERROR_DATE");

                    b.Property<DateTime?>("ErrorFixDate")
                        .HasColumnName("ERROR_FIX_DATE");

                    b.Property<string>("ErrorMessage")
                        .HasColumnName("ERROR_MESSAGE")
                        .HasMaxLength(2000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasMaxLength(2000);

                    b.Property<bool>("IsPhotoSend")
                        .HasColumnName("IS_PHOTO_SEND");

                    b.Property<int>("PackageNumber")
                        .HasColumnName("PACKAGE_NUMBER");

                    b.Property<int?>("PackageStatus")
                        .HasColumnName("PACKAGE_STATUS_KEY");

                    b.Property<string>("PackageUrl")
                        .IsRequired()
                        .HasColumnName("PACKAGE_URL")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(1000);

                    b.Property<Guid?>("RequestId")
                        .HasColumnName("REQUEST_ID");

                    b.Property<DateTime?>("SendPackageDate")
                        .HasColumnName("SEND_PACKAGE_DATE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TYPE")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<long>("UserId")
                        .HasColumnName("USER_ID");

                    b.Property<long>("UserSapNumber")
                        .HasColumnName("USER_SAP_NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Type")
                        .IsUnique();

                    b.ToTable("PACKAGE_PHOTO");
                });

            modelBuilder.Entity("Service.Photos.Dal.PhotoPackageHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnName("APPROVE_DATE");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("END_DATE");

                    b.Property<DateTime?>("ErrorDate")
                        .HasColumnName("ERROR_DATE");

                    b.Property<string>("ErrorMessage")
                        .HasColumnName("ERROR_MESSAGE")
                        .HasMaxLength(2000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasMaxLength(2000);

                    b.Property<string>("FullName")
                        .HasColumnName("FULL_NAME")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(365);

                    b.Property<long>("PackageId")
                        .HasColumnName("PACKAGE_ID");

                    b.Property<int>("PackageNumber")
                        .HasColumnName("PACKAGE_NUMBER");

                    b.Property<int?>("PackageStatus")
                        .HasColumnName("PACKAGE_STATUS_KEY");

                    b.Property<Guid?>("RequestId")
                        .HasColumnName("REQUEST_ID");

                    b.Property<int>("SapNumber")
                        .HasColumnName("SAP_NUMBER");

                    b.Property<DateTime?>("SendPackageDate")
                        .HasColumnName("SEND_PACKAGE_DATE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE");

                    b.Property<long?>("UserId")
                        .HasColumnName("USER_ID");

                    b.Property<long?>("UserSapNumber")
                        .HasColumnName("USER_SAP_NUMBER");

                    b.HasKey("Id");

                    b.ToTable("PACKAGE_PHOTO_HISTORY");
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhoto", b =>
                {
                    b.HasOne("Service.Photos.Dal.Attachment", "Attachment")
                        .WithOne()
                        .HasForeignKey("Service.Photos.Dal.ApplicationPhoto", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Service.Photos.Dal.PhotoPackage")
                        .WithMany("ApplicationPhotos")
                        .HasForeignKey("PhotoPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhotoHistory", b =>
                {
                    b.HasOne("Service.Photos.Dal.PhotoPackageHistory")
                        .WithMany("ApplicationPhotosHistory")
                        .HasForeignKey("PackageHistoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
