// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Service.Photos.Dal.Migrations
{
    [DbContext(typeof(PhotosContext))]
    partial class PhotosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<int>("AttachedBy")
                        .HasColumnName("ATTACHED_BY")
                        .HasColumnType("int");

                    b.Property<long>("AttachmentId")
                        .HasColumnName("ATTACHMENT_ID")
                        .HasColumnType("int64");

                    b.Property<string>("ErrorCode")
                        .HasColumnName("ERROR_CODE")
                        .HasColumnType("nvarchar2(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("FoundDate")
                        .HasColumnName("FOUND_DATE")
                        .HasColumnType("timestamp");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IS_DELETED")
                        .HasColumnType("bool");

                    b.Property<bool?>("IsSaved")
                        .HasColumnName("IS_SAVED")
                        .HasColumnType("bool");

                    b.Property<double>("Latitude")
                        .HasColumnName("LATITUDE")
                        .HasColumnType("binary_double");

                    b.Property<double>("Longitude")
                        .HasColumnName("LONGITUDE")
                        .HasColumnType("binary_double");

                    b.Property<int?>("ParentPhotoTypeId")
                        .HasColumnName("PARENT_PHOTO_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<long>("PhotoPackageId")
                        .HasColumnName("PACKAGE_PHOTO_ID")
                        .HasColumnType("int64");

                    b.Property<int>("PhotoTypeId")
                        .HasColumnName("PHOTO_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .IsUnique();

                    b.HasIndex("PhotoPackageId");

                    b.ToTable("APPLICATION_PHOTO");
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhotoHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<string>("ErrorCode")
                        .HasColumnName("ERROR_CODE")
                        .HasColumnType("nvarchar2(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("FoundDate")
                        .HasColumnName("FOUND_DATE")
                        .HasColumnType("timestamp");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IS_DELETED")
                        .HasColumnType("bool");

                    b.Property<double>("Latitude")
                        .HasColumnName("LATITUDE")
                        .HasColumnType("binary_double");

                    b.Property<double>("Longitude")
                        .HasColumnName("LONGITUDE")
                        .HasColumnType("binary_double");

                    b.Property<long>("PackageHistoryId")
                        .HasColumnName("PACKAGE_HISTORY_ID")
                        .HasColumnType("int64");

                    b.Property<int?>("ParentPhotoTypeId")
                        .HasColumnName("PARENT_PHOTO_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<int>("PhotoTypeId")
                        .HasColumnName("PHOTO_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("PackageHistoryId");

                    b.ToTable("APPLICATION_PHOTO_HISTORY");
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationRejectPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<long>("ApplicationId")
                        .HasColumnName("PARENT_ID")
                        .HasColumnType("int64");

                    b.Property<long>("AttachmentId")
                        .HasColumnName("ATTACHMENT_ID")
                        .HasColumnType("int64");

                    b.Property<double>("Latitude")
                        .HasColumnName("LATITUDE")
                        .HasColumnType("binary_double");

                    b.Property<double>("Longitude")
                        .HasColumnName("LONGITUDE")
                        .HasColumnType("binary_double");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<int>("Type")
                        .HasColumnName("TYPE")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .IsUnique();

                    b.ToTable("PHOTOS");
                });

            modelBuilder.Entity("Service.Photos.Dal.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<byte[]>("MiniPhoto")
                        .HasColumnName("MINI_PHOTO")
                        .HasColumnType("blob");

                    b.Property<byte[]>("Photo")
                        .HasColumnName("PHOTO")
                        .HasColumnType("blob");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("UUID")
                        .HasColumnName("UUID")
                        .HasColumnType("guid");

                    b.HasKey("Id");

                    b.ToTable("ATTACHMENT");
                });

            modelBuilder.Entity("Service.Photos.Dal.CurrentPhotoRequired", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<int>("CreditType")
                        .HasColumnName("CREDIT_TYPE_KEY")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDigital")
                        .HasColumnName("IS_DIGITAL")
                        .HasColumnType("bool");

                    b.Property<bool?>("IsRemoteSign")
                        .HasColumnName("IS_REMOTE_SIGN")
                        .HasColumnType("bool");

                    b.Property<bool>("IsRequired")
                        .HasColumnName("IS_REQUIRED")
                        .HasColumnType("bool");

                    b.Property<int>("PhotoTypeId")
                        .HasColumnName("PHOTO_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<bool>("Visibility")
                        .HasColumnName("VISIBILITY")
                        .HasColumnType("bool");

                    b.HasKey("Id");

                    b.ToTable("CURRENT_PHOTO_REQUIRED");
                });

            modelBuilder.Entity("Service.Photos.Dal.CurrentPhotoType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("CODE")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(255);

                    b.Property<int?>("DocumentType")
                        .HasColumnName("DOC_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnName("ORDER")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnName("PARENT_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<int>("TypeId")
                        .HasColumnName("TYPE_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CURRENT_PHOTO_TYPE");
                });

            modelBuilder.Entity("Service.Photos.Dal.PhotoPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<long>("ApplicationId")
                        .HasColumnName("APPL_ID")
                        .HasColumnType("int64");

                    b.Property<DateTime?>("AproveDate")
                        .HasColumnName("APROVE_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ErrorDate")
                        .HasColumnName("ERROR_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ErrorFixDate")
                        .HasColumnName("ERROR_FIX_DATE")
                        .HasColumnType("timestamp");

                    b.Property<string>("ErrorMessage")
                        .HasColumnName("ERROR_MESSAGE")
                        .HasColumnType("nvarchar2(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasColumnType("nvarchar2(2000)")
                        .HasMaxLength(2000);

                    b.Property<bool>("IsPhotoSend")
                        .HasColumnName("IS_PHOTO_SEND")
                        .HasColumnType("bool");

                    b.Property<int>("PackageNumber")
                        .HasColumnName("PACKAGE_NUMBER")
                        .HasColumnType("int");

                    b.Property<int?>("PackageStatus")
                        .HasColumnName("PACKAGE_STATUS_KEY")
                        .HasColumnType("int");

                    b.Property<string>("PackageUrl")
                        .IsRequired()
                        .HasColumnName("PACKAGE_URL")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(1000);

                    b.Property<Guid?>("RequestId")
                        .HasColumnName("REQUEST_ID")
                        .HasColumnType("guid");

                    b.Property<DateTime?>("SendPackageDate")
                        .HasColumnName("SEND_PACKAGE_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TYPE")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("timestamp");

                    b.Property<long>("UserId")
                        .HasColumnName("USER_ID")
                        .HasColumnType("int64");

                    b.Property<long>("UserSapNumber")
                        .HasColumnName("USER_SAP_NUMBER")
                        .HasColumnType("int64");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Type")
                        .IsUnique();

                    b.ToTable("PACKAGE_PHOTO");
                });

            modelBuilder.Entity("Service.Photos.Dal.PhotoPackageHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int64");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnName("APPROVE_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("END_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ErrorDate")
                        .HasColumnName("ERROR_DATE")
                        .HasColumnType("timestamp");

                    b.Property<string>("ErrorMessage")
                        .HasColumnName("ERROR_MESSAGE")
                        .HasColumnType("nvarchar2(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("ErrorText")
                        .HasColumnName("ERROR_TEXT")
                        .HasColumnType("nvarchar2(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("FullName")
                        .HasColumnName("FULL_NAME")
                        .HasColumnType("NVARCHAR2")
                        .HasMaxLength(365);

                    b.Property<long>("PackageId")
                        .HasColumnName("PACKAGE_ID")
                        .HasColumnType("int64");

                    b.Property<int>("PackageNumber")
                        .HasColumnName("PACKAGE_NUMBER")
                        .HasColumnType("int");

                    b.Property<int?>("PackageStatus")
                        .HasColumnName("PACKAGE_STATUS_KEY")
                        .HasColumnType("int");

                    b.Property<Guid?>("RequestId")
                        .HasColumnName("REQUEST_ID")
                        .HasColumnType("guid");

                    b.Property<int>("SapNumber")
                        .HasColumnName("SAP_NUMBER")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SendPackageDate")
                        .HasColumnName("SEND_PACKAGE_DATE")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("timestamp");

                    b.Property<long?>("UserId")
                        .HasColumnName("USER_ID")
                        .HasColumnType("int64");

                    b.Property<long?>("UserSapNumber")
                        .HasColumnName("USER_SAP_NUMBER")
                        .HasColumnType("int64");

                    b.HasKey("Id");

                    b.ToTable("PACKAGE_PHOTO_HISTORY");
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhoto", b =>
                {
                    b.HasOne("Service.Photos.Dal.Attachment", "Attachment")
                        .WithOne()
                        .HasForeignKey("Service.Photos.Dal.ApplicationPhoto", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Photos.Dal.PhotoPackage", null)
                        .WithMany("ApplicationPhotos")
                        .HasForeignKey("PhotoPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationPhotoHistory", b =>
                {
                    b.HasOne("Service.Photos.Dal.PhotoPackageHistory", null)
                        .WithMany("ApplicationPhotosHistory")
                        .HasForeignKey("PackageHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Service.Photos.Dal.ApplicationRejectPhoto", b =>
                {
                    b.HasOne("Service.Photos.Dal.Attachment", "Attachment")
                        .WithOne()
                        .HasForeignKey("Service.Photos.Dal.ApplicationRejectPhoto", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
