// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.PhotoPackages.Dal;

namespace Service.PhotoPackages.Dal.Migrations
{
    [DbContext(typeof(PhotoPackagesDbContext))]
    partial class PhotoPackagesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.Photo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AttachSystemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("ATTACH_SYSTEM_CODE");

                    b.Property<bool>("CanBeRetaken")
                        .HasColumnType("bool")
                        .HasColumnName("CAN_BE_RETAKEN");

                    b.Property<string>("ContentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("CONTENT_ID");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar2(100)")
                        .HasColumnName("ERROR_CODE");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar2(1000)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("PhotoPackageId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("PHOTO_PACKAGE_ID");

                    b.Property<bool>("Required")
                        .HasColumnType("bool")
                        .HasColumnName("REQUIRED");

                    b.Property<string>("ScanServerDocumentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_SERVER_DOCUMENT_ID");

                    b.Property<string>("ScanServerPageId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_SERVER_PAGE_ID");

                    b.Property<string>("ScanServerPageNumber")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_SERVER_PAGE_NUMBER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("STATUS_CODE");

                    b.Property<string>("ThumbnailContentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("THUMBNAIL_CONTENT_ID");

                    b.Property<string>("TranzWareScanId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("TRANZ_WARE_SCAN_ID");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("TYPE_CODE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id")
                        .HasName("PK_PH_PHOTO");

                    b.HasIndex("PhotoPackageId");

                    b.ToTable("PH_PHOTO");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.PhotoHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int64")
                        .HasColumnName("ID");

                    b.Property<string>("ContentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("CONTENT_ID");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar2(100)")
                        .HasColumnName("ERROR_CODE");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar2(1000)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("PHOTO_ID");

                    b.Property<string>("ScanServerDocumentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_SERVER_DOCUMENT_ID");

                    b.Property<string>("ScanServerPageId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_SERVER_PAGE_ID");

                    b.Property<string>("ScanServerPageNumber")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_SERVER_PAGE_NUMBER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("STATUS_CODE");

                    b.Property<string>("ThumbnailContentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("THUMBNAIL_CONTENT_ID");

                    b.Property<string>("TranzWareScanId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("TRANZ_WARE_SCAN_ID");

                    b.HasKey("Id")
                        .HasName("PK_PH_PHOTO_HISTORY");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_PH_PHOTO_HISTORY_PHOTO_ID");

                    b.ToTable("PH_PHOTO_HISTORY");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.PhotoPackage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("ID");

                    b.Property<long?>("AuthorSapNumber")
                        .HasColumnType("int64")
                        .HasColumnName("AUTHOR_SAP_NUMBER");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("BUCKET_ID");

                    b.Property<DateTime>("ClientBirthday")
                        .HasColumnType("date")
                        .HasColumnName("CLIENT_BIRTHDAY");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("CONTRACT_ID");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar2(100)")
                        .HasColumnName("ERROR_CODE");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar2(1000)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<double?>("Latitude")
                        .HasColumnType("binary_double")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("binary_double")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("ProcessCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar2(100)")
                        .HasColumnName("PROCESS_CODE");

                    b.Property<string>("ScanCheckerRequestId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_CHECKER_REQUEST_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("STATUS_CODE");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("TYPE_CODE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<long?>("VerifierSapNumber")
                        .HasColumnType("int64")
                        .HasColumnName("VERIFIER_SAP_NUMBER");

                    b.HasKey("Id")
                        .HasName("PK_PH_PHOTO_PACKAGE");

                    b.ToTable("PH_PHOTO_PACKAGE");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.PhotoPackageHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int64")
                        .HasColumnName("ID");

                    b.Property<long?>("AuthorSapNumber")
                        .HasColumnType("int64")
                        .HasColumnName("AUTHOR_SAP_NUMBER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar2(100)")
                        .HasColumnName("ERROR_CODE");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar2(1000)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<double?>("Latitude")
                        .HasColumnType("binary_double")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("binary_double")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("PhotoPackageId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("PHOTO_PACKAGE_ID");

                    b.Property<string>("ScanCheckerRequestId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar2(36)")
                        .HasColumnName("SCAN_CHECKER_REQUEST_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2(50)")
                        .HasColumnName("STATUS_CODE");

                    b.Property<long?>("VerifierSapNumber")
                        .HasColumnType("int64")
                        .HasColumnName("VERIFIER_SAP_NUMBER");

                    b.HasKey("Id")
                        .HasName("PK_PH_PHOTO_PACKAGE_HISTORY");

                    b.HasIndex("PhotoPackageId")
                        .HasDatabaseName("IX_PH_PHOTO_PACKAGE_HISTORY_PHOTO_PACKAGE_ID");

                    b.ToTable("PH_PHOTO_PACKAGE_HISTORY");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.Photo", b =>
                {
                    b.HasOne("Service.PhotoPackages.Dal.Models.PhotoPackage", "PhotoPackage")
                        .WithMany("Photos")
                        .HasForeignKey("PhotoPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoPackage");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.PhotoHistory", b =>
                {
                    b.HasOne("Service.PhotoPackages.Dal.Models.Photo", "Photo")
                        .WithMany("History")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.PhotoPackageHistory", b =>
                {
                    b.HasOne("Service.PhotoPackages.Dal.Models.PhotoPackage", "PhotoPackage")
                        .WithMany("History")
                        .HasForeignKey("PhotoPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoPackage");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.Photo", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Service.PhotoPackages.Dal.Models.PhotoPackage", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
